# Generated by Django 2.1.5 on 2019-02-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_cryptocurrency',
            field=models.BooleanField(default=False),
        ),
    ]
