# Generated by Django 2.1.5 on 2019-02-11 19:27

from django.db import migrations, connection
from django.db.models import Q


def set_currencies(apps, schema_editor):
    Currency = apps.get_model("currency", "Currency")

    Currency.objects.get_or_create(code="USD", name="Dollar")
    Currency.objects.get_or_create(code="BTC", name="Bitcoin")
    Currency.objects.get_or_create(code="BRL", name="Real")
    Currency.objects.get_or_create(code="EUR", name="Euro")


def reverse_set_currencies(apps, schema_editor):
    Currency = apps.get_model("currency", "Currency")

    if connection.vendor not in ["djongo", "mongodb"]:
        Currency.objects.filter(code__in=["BTC", "USD", "BRL", "EUR"]).delete()
    else:
        q = (
            Q(code__contains="BTC")
            | Q(code__contains="USD")
            | Q(code__contains="BRL")
            | Q(code__contains="EUR")
        )
        currencies_codes_queryset = Currency.objects.filter(q).values("code")
        Currency.objects.filter(code__in=currencies_codes_queryset).delete()


class Migration(migrations.Migration):

    dependencies = [("currency", "0003_quotation_backend_id")]

    operations = [
        migrations.RunPython(set_currencies, reverse_code=reverse_set_currencies)
    ]
